import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    files: ['**/*.{js,jsx,mjs,cjs}'],
    ignores: ['frontend/dist/**', 'dist/**', 'node_modules/**'],
    languageOptions: {
      globals: {
        React: 'readonly',
        process: 'readonly',
        document: 'readonly',
        window: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        localStorage: 'readonly',
        console: 'readonly',
      },
    },
    rules: {
      // Отключаем все правила стилистики
      'no-unused-vars': 'off',
      'no-undef': 'off',
      'react/react-in-jsx-scope': 'off',
      'no-cond-assign': 'off',
      'no-empty': 'off',
      'no-fallthrough': 'off',
      'no-control-regex': 'off',
      'no-prototype-builtins': 'off',
      'getter-return': 'off',
      'valid-typeof': 'off',
      'no-constant-condition': 'off',
      'no-useless-escape': 'off',
      'no-misleading-character-class': 'off',
      'no-unreachable': 'off',
      'no-dupe-keys': 'off',
      'no-dupe-args': 'off',
      'no-duplicate-case': 'off',
      'no-empty-pattern': 'off',
      'no-extra-boolean-cast': 'off',
      'no-extra-semi': 'off',
      'no-func-assign': 'off',
      'no-inner-declarations': 'off',
      'no-irregular-whitespace': 'off',
      'no-obj-calls': 'off',
      'no-sparse-arrays': 'off',
      'no-unexpected-multiline': 'off',
      'no-unsafe-finally': 'off',
      'use-isnan': 'off',
      'valid-typeof': 'off',
    },
  },
];
